build:
  version: "3.0"

accounts:
  message: "Welcome to accounts related PROD APIs "
  contactDetails:
    name: "Mudit Khanna - PROD User"
    email: "muditClient@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345