build:
  version: "1.0"

accounts:
  message: "Welcome to accounts related local APIs "
  contactDetails:
    name: "Mudit Khanna - Developer"
    email: "mudit@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345