build:
  version: "2.0"

accounts:
  message: "Welcome to accounts related QA APIs "
  contactDetails:
    name: "Mudit Khanna - QA Tester"
    email: "muditTester@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345