spring:
  application:
    name: "config-server"

  profiles:
    active: git

  cloud:
    config:
      server:
        git:
          uri: "https://github.com/muditkhanna98/config.git"
          default-label: "main"
          timeout: 5
          clone-on-start: true
          force-pull: true

server:
  port: 8071